import { execFileSync } from "node:child_process";
import { appendFileSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import type { Index, IndexEntry } from "@weft/schema";

/**
 * Render the PR body for a single-harness catalog bump from REAL data — diffing the committed
 * (`HEAD:index.json`) catalog against the freshly rebuilt working-tree `index.json`. The body shape
 * is identical for every harness (that's the point: consistent, reviewable PRs), and the resolved
 * version + branch name are emitted to `$GITHUB_OUTPUT` so the workflow needn't be told the version
 * up front. Run AFTER `WEFT_BUILD_ONLY=<id> pnpm build`.
 *
 * argv[2] = harness id.
 */
const millDir = join(dirname(fileURLToPath(import.meta.url)), "..");
const id = process.argv[2];
if (!id) throw new Error("usage: render-bump-pr <harness-id>");

const entryOf = (idx: Index | undefined, want: string): IndexEntry | undefined =>
  idx?.entries.find((e) => e.id === want);

const after = JSON.parse(readFileSync(join(millDir, "index.json"), "utf8")) as Index;
let before: Index | undefined;
try {
  before = JSON.parse(execFileSync("git", ["show", "HEAD:index.json"], { cwd: millDir, encoding: "utf8" })) as Index;
} catch {
  before = undefined; // first ever build, or index.json not yet committed
}

const a = entryOf(after, id);
if (!a) throw new Error(`render-bump-pr: "${id}" not found in built index.json`);
const b = entryOf(before, id);

const from = b?.latest ?? null;
const to = a.latest;
const branch = `livecheck/${id}-${to}`;

// ── spool hash changes (the substance of the diff) ──
const shaMap = (e: IndexEntry | undefined): Map<string, string> => {
  const m = new Map<string, string>();
  for (const v of e?.versions ?? []) for (const s of v.spools) m.set(`${v.version} · ${s.cli}/${s.scope}`, s.spoolSha);
  return m;
};
const short = (sha: string): string => sha.replace(/^sha256:/, "").slice(0, 12);
const beforeSha = shaMap(b);
const afterSha = shaMap(a);
const changes: string[] = [];
for (const [k, sha] of afterSha) {
  const old = beforeSha.get(k);
  if (old === undefined) changes.push(`- 🆕 \`${k}\` → \`${short(sha)}…\``);
  else if (old !== sha) changes.push(`- ♻️ \`${k}\`  \`${short(old)}…\` → \`${short(sha)}…\``);
}
for (const k of beforeSha.keys()) if (!afterSha.has(k)) changes.push(`- ❌ \`${k}\` (removed)`);

const lines: (string | null)[] = [
  `## 📦 Catalog bump: \`${id}\` → \`${to}\``,
  "",
  "Automated by **livecheck** — upstream published a new version and this PR carries the rebuilt " +
    "catalog (`index.json` + spools), produced on a clean CI runner with the real upstream installer " +
    "and the machine-path portability gate.",
  "",
  "| | |",
  "| --- | --- |",
  `| Harness | \`${id}\` — ${a.displayName} |`,
  `| Version | ${from ? `\`${from}\`` : "_(new)_"} → **\`${to}\`** |`,
  `| CLIs | ${a.clis.join(", ")} |`,
  a.homepage ? `| Source | ${a.homepage} |` : null,
  "",
  "### Spool changes",
  changes.length ? changes.join("\n") : "_No spool hash changes detected (metadata-only bump)._",
  "",
  "### Reviewer checklist",
  `- [ ] Version bump matches the upstream release (\`${to}\`)`,
  "- [ ] Only this harness's files changed — no unrelated catalog churn",
  "- [ ] `verify-catalog` check is green",
  `- [ ] Merge to publish \`${to}\` to the catalog`,
  "",
  `<sub>Generated by weft-mill \`bump.yml\` · branch \`${branch}\`</sub>`,
];

writeFileSync(join(millDir, "pr-body.md"), `${lines.filter((l): l is string => l !== null).join("\n")}\n`);

const out = process.env.GITHUB_OUTPUT;
if (out) {
  appendFileSync(out, `version=${to}\n`);
  appendFileSync(out, `branch=${branch}\n`);
  appendFileSync(out, `from=${from ?? ""}\n`);
}
console.log(`Rendered PR body for ${id}: ${from ?? "(new)"} → ${to} (branch ${branch})`);
